sudo: required

services:
  - postgresql

addons:
  postgresql: 9.5

language: php

php:
  - 7.1

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-dist --no-scripts --no-progress --no-suggest --optimize-autoloader --classmap-authoritative

before_script:
  - psql -c 'CREATE DATABASE remembrall_test;' -U postgres
  - psql -U postgres remembrall_test < Tests/TestCase/schema.sql

after_script:
    - >
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config Tests/.coveralls.yml

script:
  - ./vendor/bin/phing ci

after_failure:
  - for i in $(find Tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

cache:
    directories:
      - $HOME/.composer/cache
