sudo: required

services:
  - postgresql
  - redis-server

addons:
  postgresql: 9.5

language: php

php:
  - 7.1

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-dist --no-scripts --no-progress --no-suggest --optimize-autoloader --classmap-authoritative

before_script:
  - cp -f Tests/TestCase/.config.travis.ini Tests/TestCase/.config.local.ini
  - sudo cp -f ./docker/sendmail /usr/sbin/fake-sendmail && sudo chmod +x /usr/sbin/fake-sendmail
  - psql -c 'CREATE DATABASE remembrall_test;' -U postgres
  - psql -U postgres remembrall_test < Tests/TestCase/schema.sql

script:
  - ./vendor/bin/phing ci

after_script:
    - >
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config Tests/.coveralls.yml

after_failure:
  - for i in $(find Tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

#before_deploy:
#  - openssl aes-256-cbc -K $encrypted_c4f6e40ac2f7_key -iv $encrypted_c4f6e40ac2f7_iv -in active24.enc -out active24 -d
#  - chmod 600 active24
#  - mkdir -p ~/.ssh
#  - mv active24 ~/.ssh/id_rsa
#  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
#
#deploy:
#  provider: script
#  skip_cleanup: true
#  script: ./vendor/bin/dep deploy
#  on:
#    branch: master

cache:
    directories:
      - $HOME/.composer/cache
