version: '3'
services:
    postgres:
      image: postgres:alpine
      container_name: remembrall-postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=remembrall
      ports:
        - 5432:5432
    adminer:
      image: adminer:standalone
      container_name: remembrall-adminer
      ports:
        - 8080:8080
    php-fpm:
      build: ./php-fpm
      working_dir: /var/www/Remembrall
      volumes:
          - ./..:/var/www/Remembrall
          - ./sendmail:/usr/sbin/fake-sendmail
          - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    nginx:
      image: nginx:alpine
      volumes:
          - ./..:/var/www/Remembrall
          - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
          - ./nginx/access.log:/var/log/nginx/access.log
          - ./nginx/error.log:/var/log/nginx/error.log
      ports:
        - 80:80